{{- if .Values.odoo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo-stack.fullname" . }}-odoo
  labels:
    {{- include "odoo-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: odoo
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "odoo-stack.odooSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.odooPort }}
      targetPort: {{ .Values.odoo.port }}
      protocol: TCP
{{- end }}
