{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo-stack.fullname" . }}-secret
  labels:
    {{- include "odoo-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
  ODOO_DB_PASSWORD: {{ .Values.secret.odooDbPassword | quote }}
{{- end }}
