"""Lifecycle of a tenant database: create, provision, duplicate, suspend, delete."""
from __future__ import annotations

import logging
import shutil
from dataclasses import dataclass
from datetime import date, timedelta

from sqlalchemy.orm import Session

from app.config import settings
from app.models.enums import TenantStatus
from app.models.plan import Plan
from app.models.tenant import Tenant
from app.services import limits as limits_service
from app.services import plan_service, tenant_service
from app.services.odoo_client import OdooError

_logger = logging.getLogger(__name__)


class ProvisionError(RuntimeError):
    """Raised when provisioning / deletion of a tenant database fails."""


@dataclass
class ProvisionResult:
    """Outcome of a provisioning run."""

    db_name: str
    installed_modules: list[str]
    pushed_params: dict[str, str]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def default_admin_password() -> str:
    """Password assigned to the client's admin user at creation time."""
    # A strong random password is generated by the caller; this is only a fallback.
    from app.security import generate_token  # noqa: PLC0415

    return generate_token(12)


def _fresh_db_client() -> "OdooClient":  # noqa: F821
    from app.services.odoo_client import OdooClient  # noqa: PLC0415

    return OdooClient(db="postgres")


# ---------------------------------------------------------------------------
# Create
# ---------------------------------------------------------------------------
def create_database(db_name: str, *, demo: bool = False, lang: str = "en_US",
                    admin_login: str = "admin", admin_password: str = "admin") -> bool:
    """Create and initialise a database through the Odoo db service (token authorised)."""
    client = _fresh_db_client()
    try:
        if client.database_exists(db_name):
            raise ProvisionError(f"Database {db_name!r} already exists")
        client.create_database(
            db_name,
            demo=demo,
            lang=lang,
            admin_password=admin_password,
            admin_login=admin_login,
        )
    except OdooError as exc:
        raise ProvisionError(f"database creation failed: {exc}") from exc
    finally:
        client.close()
    return True


def provision(session: Session, tenant: Tenant, *, plan: Plan | None = None,
              admin_password: str = "admin", demo: bool = False, lang: str = "en_US") -> ProvisionResult:
    """Full first-time provisioning of a tenant.

    Steps: create the database, store credentials, install plan apps, push the
    plan limits. Idempotent enough to be re-run for the app/limit part.
    """
    plan = plan or tenant.plan
    if not tenant.provisioned:
        create_database(
            tenant.db_name, demo=demo, lang=lang,
            admin_login=tenant.admin_login, admin_password=admin_password,
        )
        tenant_service.store_admin_password(tenant, admin_password)
        tenant.provisioned = True

    client = tenant_service.authenticated_client(tenant)
    try:
        installed_before = client.installed_modules()
        plan_diff = plan_service.apply_plan(client, plan)
        pushed = limits_service.push_limits(client, tenant)
        installed_after = client.installed_modules()
    finally:
        client.close()

    tenant.last_update_at = _now()
    return ProvisionResult(
        db_name=tenant.db_name,
        installed_modules=sorted(set(installed_after) - set(installed_before)) or plan_diff.to_install,
        pushed_params=pushed,
    )


# ---------------------------------------------------------------------------
# Duplicate
# ---------------------------------------------------------------------------
def duplicate(session: Session, source: Tenant, *, subdomain: str, db_name: str,
              name: str | None = None) -> Tenant:
    """Create a new tenant as a copy of an existing one (DB + filestore)."""
    client = _fresh_db_client()
    try:
        if client.database_exists(db_name):
            raise ProvisionError(f"Database {db_name!r} already exists")
        client.duplicate_database(source.db_name, db_name)
    except OdooError as exc:
        raise ProvisionError(f"database duplication failed: {exc}") from exc
    finally:
        client.close()

    clone = Tenant(
        name=name or f"{source.name} (copy)",
        subdomain=subdomain,
        db_name=db_name,
        contact_name=source.contact_name,
        email=source.email,
        phone=source.phone,
        country=source.country,
        tax_id=source.tax_id,
        plan_id=source.plan_id,
        status=TenantStatus.TRIAL.value,
        start_date=date.today(),
        expiry_date=date.today() + timedelta(days=source.trial_days),
        trial_days=source.trial_days,
        max_users=source.max_users,
        max_warehouses=source.max_warehouses,
        max_companies=source.max_companies,
        max_storage_mb=source.max_storage_mb,
        max_db_size_mb=source.max_db_size_mb,
        admin_login=source.admin_login,
        admin_password_enc=source.admin_password_enc,
        provisioned=True,
    )
    session.add(clone)
    session.flush()
    return clone


# ---------------------------------------------------------------------------
# Delete
# ---------------------------------------------------------------------------
def delete(session: Session, tenant: Tenant, *, drop_filestore: bool = True) -> None:
    """Permanently drop a tenant's database (and optionally its filestore)."""
    client = _fresh_db_client()
    try:
        if client.database_exists(tenant.db_name):
            client.drop_database(tenant.db_name)
    except OdooError as exc:
        raise ProvisionError(f"database drop failed: {exc}") from exc
    finally:
        client.close()

    if drop_filestore:
        fs = _filestore(tenant.db_name)
        if fs.exists():
            shutil.rmtree(fs, ignore_errors=True)


def _filestore(db_name: str):
    from pathlib import Path  # noqa: PLC0415

    return Path(settings.odoo_data_dir) / "filestore" / db_name


# ---------------------------------------------------------------------------
# Suspend / activate
# ---------------------------------------------------------------------------
def suspend(session: Session, tenant: Tenant) -> None:
    """Set the tenant read-only and push the status to the client."""
    tenant.maintenance_mode = True
    tenant_service.set_status(tenant, TenantStatus.SUSPENDED)
    tenant_service.push_status(tenant)


def activate(session: Session, tenant: Tenant) -> None:
    """Reactivate a tenant and push the status to the client."""
    tenant.maintenance_mode = False
    tenant_service.set_status(tenant, TenantStatus.ACTIVE)
    tenant_service.push_status(tenant)


def _now():
    from datetime import datetime, timezone  # noqa: PLC0415

    return datetime.now(timezone.utc)
